### ISSUE TITLE
Badge on menu items?

### ISSUE THREAD

**Issue by pnome** [andreamazz/SlideOutNavigation#89]
Using [self.slideoutController setBadgeValue:@"3" forTag:4];  I was expecting/hoping to see a badge on the actual menu row.  

When the global badge shows up on the slide out menu button it motivates the user to tap it to see what the new notifications are.  If there's no badge on the actual row items they don't know where to tap once the menu is open.  Am I missing something?

If there isn't a badge for the row items is there another way I can draw attention to the relevant row or dynamically change the text or menu icon?

Thanks,
Joe

**Comment by andreamazz** [comment]
Hi @pnome 
`setBadgeValue:forTag:` should indeed set the badge on the menu item. You can see this behaviour in the sample project:
<img width="487" alt="screen shot 2015-10-30 at 11 27 42" src="https://cloud.githubusercontent.com/assets/570797/10843427/45da0da0-7ef9-11e5-86ac-5b9f0c3f0d5e.png">

Can you post part of the code you are using?

**Comment by pnome** [comment]
Ah.  I expecting the badge to appear on the icon.  I didn’t have the page
sliding over far enough so the badge was covered.

Thanks for the quick response.

On Fri, Oct 30, 2015 at 10:28 AM, Andrea Mazzini <notifications@github.com>
wrote:

> Hi @pnome <https://github.com/pnome>
> setBadgeValue:forTag: should indeed set the badge on the menu item. You
> can see this behaviour in the sample project:
> [image: screen shot 2015-10-30 at 11 27 42]
> <https://cloud.githubusercontent.com/assets/570797/10843427/45da0da0-7ef9-11e5-86ac-5b9f0c3f0d5e.png>
>
> Can you post part of the code you are using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andreamazz/SlideOutNavigation/issues/89#issuecomment-152487012>
> .
>



-- 
----------------------------------------------------------------
Drummer, available for session work, tours, etc.

w: joecrabtree.com
f: facebook.com/joe.crabtree.drums
t: @joecrabtree
m: +44 7941370458
----------------------------------------------------------------

**Comment by andreamazz** [comment]
:+1:
